### ISSUE TITLE
is whisper lack of compatibility an exception ?

### ISSUE THREAD

**Issue by flutter-painter** [Telosnex/fonnx#4]
Quoting https://github.com/Telosnex/fonnx/tree/main/example/assets/models/whisper : 
> Only macOS ARM is currently supported. To deliver cross-platform support, the [ONNX runtime extensions](https://github.com/microsoft/onnxruntime-extensions) library needs to be compiled into binaries for macOS Intel, Linux, and Windows. Additionally, iOS and Android will need to take a dependency on the corresponding CocoaPod/Android package.

Could you please elaborate on this limitation ?
Is it specific to whisper ? Is it because you created the ONNX using Olive ?
Or is it specific to speech to text on Flutter ?

**Comment by jpohhhh** [comment]
That's an excellent question, it's somewhat about Olive, in a sentence, it's because each platform needs the ONNX Runtime Extensions code library to run the optimized Whisper that we got from Olive. 

A standard Whisper model isn't all in one model, nor does it give Strings as outputs. 
Instead, lets say it gives List<int> as outputs, aka tokens.
Then, we'd write a tokenizer, and use the tokenizer to convert List<int> to String.

Olive does a bunch of stuff that goes over my head  - I know how to get an arbitrary model to ONNX, but don't grok model structure.

But let's focus again on the standard Whisper output = List<int>, our/Olive Whisper output = String.

The Olive optimization isn't _actually_ embedding the tokenizer in the model. 
Instead, it's using a supplementary code library for ONNX, the ONNX Runtime Extensions, that implements the tokenizer in C.

To get our Whisper / Olive Whisper / optimized Whisper, each platform needs to have the ONNX Runtime Extensions code library, and also have it loaded when needed.

That's not necessarily hard: ex. [this commit](https://github.com/Telosnex/fonnx/commit/db3bf5d00e6db63af10fd15a2c423bac21f93a0f) added it for Linux and you can see its relatively small. Just down my personal priority list, for now. I'm working towards getting a baseline GPT wrapper app, and I will eventually get around to it, I want the app to have parity with the ChatGPT app, which also has TTS.

**Comment by flutter-painter** [comment]
This is great news !
So whisper is an exception. It might not be the only models that is tricky to adapt, but we can assume that most models should be available on all platforms.
ps : What is ORT ?

**Comment by flutter-painter** [comment]
ONNX Runtime Format... https://onnxruntime.ai/docs/performance/model-optimizations/ort-format-models.html
